---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: group-apps
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: base/
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: tkgm-autoscale

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: clustergroup-gitops
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
  - name: group-apps
    namespace: tanzu-continuousdelivery-resources
  interval: 1m0s
  path: workload-cluster/
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-name-secret
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: tkgm-autoscale