apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  serviceAccountName: cluster-autoscaler-install-sa
  packageRef:
    refName: cluster-autoscaler.tanzu.vmware.com
    versionSelection:
      constraints: 1.28.0+vmware.1-tkg.1
  values:
  - secretRef:
      name: cluster-autoscaler-values
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-values
  namespace: kube-system
stringData:
  values.yml: |
    clusterConfig:
      clusterName: ${cluster_name}
      clusterNamespace: default
    arguments:
      extraArguments:
      - enforce-node-group-min-size=true
