---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler-install-sa
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-binding
subjects:
- kind: ServiceAccount
  name: cluster-autoscaler-install-sa
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin