apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mutate.yml
- rbac.yml
configMapGenerator:
- name: autoscale-controller
  namespace: autoscale-webhook
  files:
  - mutate.py